LogLevel warn
SystemGroup lpadmin
ServerAlias *
DefaultEncryption never

# Listen on all interfaces
Port 631

# Disable printer sharing by default
Browsing Off
DefaultAuthType Basic

WebInterface Yes

# Restrict root location
<Location />
  Order allow,deny
  Allow 192.168.0.0/16
  Allow 172.17.0.0/16
</Location>

# Require auth for admin
<Location /admin>
  AuthType Basic
  Require user @SYSTEM
  Order allow,deny
  Allow 192.168.0.0/16
  Allow 172.17.0.0/16
</Location>

<Location /admin/conf>
  AuthType Basic
  Require user @SYSTEM
  Order allow,deny
  Allow 192.168.0.0/16
  Allow 172.17.0.0/16
</Location>

# Protect printers
<Location /printers>
  Order allow,deny
  Allow 192.168.0.0/16
  Allow 172.17.0.0/16
</Location>